name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  RUST_TOOLCHAIN: stable
  TOOLCHAIN_PROFILE: minimal

jobs:
  backend-ci:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - platform: 'macos-latest'
            args: '--verbose --target universal-apple-darwin'
          - platform: 'ubuntu-latest'
            args: '--verbose'
          - platform: 'windows-latest'
            args: '--verbose'
    name: Run cargo fmt and cargo clippy
    runs-on: ${{ matrix.settings.platform }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: ${{ env.TOOLCHAIN_PROFILE }}
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
          components: rustfmt, clippy
      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: "src-tauri -> src-tauri/target"
      - name: install dependencies (ubuntu only)
        if: matrix.settings.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev libgtk-3-dev
      - name: Run ci
        run: |
          cd src-tauri
          make ci
